name: Test conan recipe
run-name: test
on: [push, workflow_dispatch]
jobs:
  test-conan-recipe:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: Install conan
        run: pip install conan

      - name: Detect conan profile
        run: conan profile detect

      # - name: Build the recipe
      #   # temporarily only target x86 to speed up build process during testing
      #   run: |
      #     conan create recipes/llvm/all --version=21.1.8 \
      #       -o llvm/*:targets=X86 \
            # -o llvm/*:enable_projects="clang"

      - name: Install test conan package
        run: |
          mkdir ~/conan_cache
          export CONAN_HOME=~/conan_cache
          conan profile detect
          mkdir build
          conan install --requires=zlib/1.3.1 --output-folder=build --build="*"
          tree

      - name: Upload the conan directory for inspection for testing
        uses: actions/upload-artifact@v4
        with:
          name: conan-dir
          path: ~/conan_cache
          retention-days: 1
