name: Test conan recipe
run-name: test
on: [push, workflow_dispatch]
jobs:
  test-conan-recipe:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: Install conan
        run: pip install conan

      - name: Detect conan profile
        run: conan profile detect

      # - name: Build the recipe
      #   # temporarily only target x86 to speed up build process during testing
      #   run: |
      #     mkdir ~/conan_cache
      #     export CONAN_HOME=~/conan_cache
      #     conan profile detect
      #     mkdir build
      #     conan create recipes/llvm/all --version=21.1.8 \
      #       -o llvm/*:targets=X86 \
      #       -o llvm/*:enable_projects="clang"
      #     conan cache clean "*"
      
      - name: Cache conan directory
        uses: actions/cache@v4
        with:
          # The directory you want to cache
          path: ~/conan_cache
          # A unique key for this cache
          key: ${{ runner.os }}-node

      - name: External test for recipe
        run: |
          cd test
          mkdir build
          export CONAN_HOME=~/conan_cache
          conan install conanfile.txt --output-folder=build --build=never
          cmake -S . -B build -DCMAKE_TOOLCHAIN_FILE=./build/generators/conan_toolchain.cmake
          cmake --build build
          ./build/test

